version: "3.9"
services:
  server:
    build: .
    ports:
      - "4000:4000"
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_USER="docker"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
